## 备注前面有单个# 的表示默认无需配置
## 正常情况下只需配置sqlResourcesDir\translateConfig\unifyFieldsHandler\debug 四个参数即可
spring:
   sqltoy:
      ## sqlResourcesDir 常用配置，如多个路径用;符号分割
      sqlResourcesDir: /com/sagframe/modules
      ## translateConfig 常用配置,使用缓存翻译时需要配置
      translateConfig: classpath:sqltoy-translate.xml
      ## 开发阶段设置debug,便于打印执行的sql,默认为false
      debug: true
      ## functionConverts 跨数据库函数替换,如单一数据库类型则无需设置
      #functionConverts: default
      ## unifyFieldsHandler 统一对createTime、updateTime、createBy、updateBy 进行统一赋值的处理类
      #unifyFieldsHandler: com.sagframe.sqltoy.plugins.SqlToyUnifyFieldsHandler
      ## dialect 如单一数据库可设置
      #dialect: mysql
      ## 默认batchSize为200
      #batchSize: 200
      ## 设置分页查询最大提取数据记录,防止过多数据获取,默认100000
      #pageFetchSizeLimit: 50000
      #printSqlStrategy: error
      ## sql执行多少毫秒需要打印,默认30秒
      #printSqlTimeoutMillis: 30000
      ## elastic 如未使用可以不用配置
      elastic:
         ## 多个elastic地址默认使用地址，对应id
         defaultId: default
         endpoints:
               ## 单个地址id
               -id: default
               ## es对应的地址,如果是集群多个地址则用;分割
               url: http://192.168.56.104:9200
               ## es版本,可以是x.x 或x.x.x
               version: 7.5
               username: elastic
               password: elastic
               
            
                  
             
              